{{ if .Values.includeQdrantVersionsCRD }}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  name: qdrantversions.qdrant.io
spec:
  group: qdrant.io
  names:
    kind: QdrantVersion
    listKind: QdrantVersionList
    plural: qdrantversions
    shortNames:
    - qv
    - qvs
    singular: qdrantversions
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.version
      name: Version
      type: string
    - jsonPath: .spec.isDefault
      name: IsDefault
      type: boolean
    - jsonPath: .spec.unavailable
      name: Unavailable
      type: boolean
    - jsonPath: .metadata.isEndOfLife
      name: IsEndOfLife
      type: boolean
    name: v1
    schema:
      openAPIV3Schema:
        description: QdrantVersion is the Schema for the qdrantversions API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: QdrantVersionSpec defines the desired state of QdrantVersion
            properties:
              accountIds:
                description: If set, this version can only be used by accounts with
                  given IDs.
                items:
                  type: string
                type: array
              accountPrivileges:
                description: If set, this version can only be used by accounts that
                  have been given the listed privileges.
                items:
                  type: string
                type: array
              image:
                description: |-
                  Full docker image to use for this version.
                  If empty, a default image will be derived from Version (and qdrant/qdrant is assumed).
                type: string
              isDefault:
                default: false
                description: |-
                  If set, this version is default for new clusters on Cloud.
                  There should be only 1 Qdrant version in the platform set as default.
                type: boolean
              isEndOfLife:
                default: false
                description: If set, this version is no longer actively supported.
                type: boolean
              releaseNotesURL:
                description: Release Notes URL for the specified version
                type: string
              remarks:
                description: General remarks for human reading
                type: string
              unavailable:
                default: false
                description: If set, this version cannot be used for new clusters.
                type: boolean
              version:
                description: |-
                  Version number (should be semver compliant).
                  E.g. "v1.10.1"
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
{{ end }}
